# Generated by Django 3.2 on 2021-05-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210502_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='house_ownership',
            field=models.CharField(blank=True, choices=[('Owned', 'Owned'), ('Leased', 'Leased'), ('Rented', 'Rented')], max_length=30, null=True),
        ),
    ]
