# Generated by Django 3.2 on 2021-05-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
