# Generated by Django 3.2 on 2021-05-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
