# Generated by Django 3.2 on 2021-05-29 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_volunteer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='way_of_contribution',
            field=models.CharField(choices=[('From Home', 'Volunteer From Home'), ('Outdoor', 'Volunteer Outdoor')], max_length=200, null=True),
        ),
    ]
