# Generated by Django 3.2 on 2021-05-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210529_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
