# Generated by Django 3.2 on 2021-04-24 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('age', models.CharField(max_length=4, null=True)),
                ('monthly_income', models.IntegerField(null=True)),
                ('relation', models.CharField(max_length=50, null=True)),
                ('verified', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('requested_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('other_financial_assistance', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20, null=True)),
                ('category', models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], max_length=20, null=True)),
                ('is_orphan', models.BooleanField(blank=True, null=True)),
                ('death_cert', models.FileField(blank=True, null=True, upload_to='')),
                ('name_of_school', models.CharField(blank=True, max_length=100, null=True)),
                ('location_of_school', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('fee_structure', models.FileField(blank=True, null=True, upload_to='')),
                ('date_of_initiation', models.DateTimeField(blank=True, null=True)),
                ('nature_of_aid', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_cost_cert', models.FileField(blank=True, null=True, upload_to='')),
                ('nature_of_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('admitted_in_hospital', models.BooleanField(blank=True, null=True)),
                ('estimation_letter', models.FileField(blank=True, null=True, upload_to='')),
                ('name_of_medicine', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Unmarried', 'Unmarried'), ('Married', 'Married'), ('Single', 'Single'), ('Widow', 'Widow')], max_length=20, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.category')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
