# Generated by Django 3.2 on 2021-04-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='nature_of_hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
