# Generated by Django 3.2 on 2021-04-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_case_nature_of_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='nature_of_hospital',
            new_name='name_of_hospital',
        ),
    ]
