# Generated by Django 3.2 on 2021-04-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
        ('projects', '0003_rename_nature_of_hospital_case_name_of_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='case',
            name='guardian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
