# Generated by Django 3.2 on 2021-05-01 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210427_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='admitted_in_hospital',
        ),
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.RemoveField(
            model_name='case',
            name='date_of_initiation',
        ),
        migrations.RemoveField(
            model_name='case',
            name='death_cert',
        ),
        migrations.RemoveField(
            model_name='case',
            name='estimated_cost_cert',
        ),
        migrations.RemoveField(
            model_name='case',
            name='estimation_letter',
        ),
        migrations.RemoveField(
            model_name='case',
            name='fee_structure',
        ),
        migrations.RemoveField(
            model_name='case',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='case',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='case',
            name='is_orphan',
        ),
        migrations.RemoveField(
            model_name='case',
            name='location_of_school',
        ),
        migrations.RemoveField(
            model_name='case',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name_of_hospital',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name_of_medicine',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name_of_school',
        ),
        migrations.RemoveField(
            model_name='case',
            name='nature_of_aid',
        ),
        migrations.RemoveField(
            model_name='case',
            name='nature_of_disease',
        ),
        migrations.AddField(
            model_name='case',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EducationalCase',
            fields=[
                ('case_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.case')),
                ('is_orphan', models.BooleanField(blank=True, null=True)),
                ('death_cert', models.FileField(blank=True, null=True, upload_to='')),
                ('guardian', models.CharField(blank=True, max_length=200, null=True)),
                ('name_of_school', models.CharField(blank=True, max_length=100, null=True)),
                ('location_of_school', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('fee_structure', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('projects.case',),
        ),
        migrations.CreateModel(
            name='GeneralCase',
            fields=[
                ('case_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.case')),
                ('date_of_initiation', models.DateTimeField(blank=True, null=True)),
                ('nature_of_aid', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_cost_cert', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('projects.case',),
        ),
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('case_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.case')),
                ('nature_of_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('admitted_in_hospital', models.BooleanField(blank=True, null=True)),
                ('name_of_hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('estimation_letter', models.FileField(blank=True, null=True, upload_to='')),
            ],
            bases=('projects.case',),
        ),
        migrations.CreateModel(
            name='MedicineCase',
            fields=[
                ('case_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.case')),
                ('nature_of_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('name_of_hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('estimation_letter', models.FileField(blank=True, null=True, upload_to='')),
                ('name_of_medicine', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('projects.case',),
        ),
        migrations.CreateModel(
            name='ProvisionalCase',
            fields=[
                ('case_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.case')),
                ('marital_status', models.CharField(blank=True, choices=[('Unmarried', 'Unmarried'), ('Married', 'Married'), ('Single', 'Single'), ('Widow', 'Widow')], max_length=20, null=True)),
            ],
            bases=('projects.case',),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
