# Generated by Django 3.2 on 2021-05-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210501_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcase',
            name='death_cert',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red')], default='Orange', max_length=20, null=True),
        ),
    ]
