# Generated by Django 3.2 on 2021-05-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='total_collected',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
