# Generated by Django 3.2 on 2021-05-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_case_total_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalcase',
            name='date_of_initiation',
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_initiation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
