# Generated by Django 3.2 on 2021-05-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210503_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_of_initiation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
