# Generated by Django 3.2 on 2021-05-08 08:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_case_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
