# Generated by Django 3.2 on 2021-05-11 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_alter_case_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdonation',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='city',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='country',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='state',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='projectdonation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
