# Generated by Django 3.2 on 2021-05-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210511_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdonation',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='pan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectdonation',
            name='phone_number',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
