# Generated by Django 3.2 on 2021-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210513_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdonation',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
