# Generated by Django 3.2 on 2021-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_projectdonation_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdonation',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
