# Generated by Django 3.2 on 2021-05-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projectdonation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
