# Generated by Django 3.2 on 2021-06-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_case_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Green', 'Green'), ('Orange', 'Orange'), ('Red', 'Red'), ('Closed', 'Closed')], default='Orange', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ExtraDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.case')),
            ],
        ),
        migrations.CreateModel(
            name='ClosedDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(blank=True, null=True, upload_to='')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.case')),
            ],
        ),
    ]
