# Generated by Django 3.2 on 2021-05-31 15:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210527_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
