# Generated by Django 3.2 on 2021-05-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlightimages',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotlight.mediaspotlight'),
        ),
    ]
