# Generated by Django 3.2 on 2021-05-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0002_spotlightimages_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaspotlight',
            name='date_created',
        ),
        migrations.AddField(
            model_name='mediaspotlight',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
    ]
