# Generated by Django 3.2 on 2021-05-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0003_auto_20210529_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaspotlight',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
